### ISSUE TITLE
Default config file attempts to load CModel code

### ISSUE THREAD

**Issue by jtmyles** [lsst/obs_subaru#154]
https://github.com/lsst/obs_subaru/blob/master/config/forcedPhotCcd.py#L7 loads cmodel.py, but CModel doesn't yet implement forced photometry when WCSs differ, leading to a fatal error when attempting to use forcedPhotCcd.py to do forced photometry on individual exposures. This issue (and a short term fix by clobbering the config file passed to the command-line task) is described in further detail here: https://community.lsst.org/t/forcedphotccd-py-fails-to-perform-measurement-due-to-wcs-issue/3233. @PaulPrice

**Comment by PaulPrice** [comment]
[DM-15727](https://jira.lsstcorp.org/browse/DM-15727).

**Comment by PaulPrice** [comment]
Fixed in #155.
